version: '3.8'
services:
  Starwars-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: newtons
      POSTGRES_PASSWORD: newton123
      POSTGRES_DB: Starwars
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: newtons
      POSTGRES_PASSWORD: newton123
      POSTGRES_DB: Starwars
    networks:
      - freecodecamp
networks:
  freecodecamp: